#!/usr/bin/env node
/** Structural documentation checks only; no application or infrastructure is tested. */
import {readFileSync,readdirSync,statSync,existsSync} from 'node:fs';
import {resolve,dirname,extname,relative,basename} from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');const read=p=>readFileSync(resolve(root,p),'utf8');const rows=[];
function check(name,fn){try{fn();rows.push({name,status:'PASS'});}catch(e){rows.push({name,status:'FAIL',error:e.message});}}
function walk(dir){return readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const p=resolve(dir,e.name);return e.isDirectory()?walk(p):[p];});}
const deliveredFiles=existsSync(resolve(root,'.git'))
  ? [...new Set(execFileSync('git',['ls-files','--cached','--others','--exclude-standard','-z'],{cwd:root,encoding:'utf8'}).split('\0').filter(Boolean))].map(p=>resolve(root,p)).filter(existsSync)
  : walk(root);
const ts=JSON.parse(read('docs/execution/tasks.json')).tasks;const ids=ts.map(x=>x.id);
const original=['S01','S02',...Array.from({length:44},(_,i)=>'B'+String(i+1).padStart(2,'0')),...Array.from({length:26},(_,i)=>'F'+String(i+1).padStart(2,'0')),...Array.from({length:6},(_,i)=>'R'+String(i+1).padStart(2,'0')),...Array.from({length:10},(_,i)=>'BV'+(201+i)),...Array.from({length:5},(_,i)=>'FV'+(201+i)),'RV201'];
check('122 lots uniques ; 106 identifiants antérieurs préservés',()=>{assert.equal(ts.length,122);assert.equal(new Set(ids).size,122);const prior=JSON.parse(read('MANIFEST.json')).prior_task_ids_preserved;assert.equal(prior.length,106);prior.forEach(x=>assert.ok(ids.includes(x),x));original.forEach(x=>assert.ok(ids.includes(x),x));});
check('Ordre continu S2 B72 F40 R8',()=>{for(const [p,n]of Object.entries({S:2,B:72,F:40,R:8}))assert.equal(ts.filter(x=>x.phase===p).length,n);ts.forEach((x,i)=>assert.equal(x.execution_order,i+1));const order=ts.map(x=>({S:0,B:1,F:2,R:3})[x.phase]);order.forEach((x,i)=>{if(i)assert.ok(order[i-1]<=x);});});
check('Communauté avant les gates et audits concernés',()=>{for(let i=1;i<=8;i++)assert.ok(ids.indexOf('BC0'+i)<ids.indexOf('B39'));assert.ok(ids.indexOf('BV201')<ids.indexOf('BC07'));assert.ok(ids.indexOf('B44')<ids.indexOf('F01'));for(let i=1;i<=3;i++)assert.ok(ids.indexOf('FC0'+i)<ids.indexOf('F23'));assert.ok(ids.indexOf('FC04')<ids.indexOf('F25'));});
check('Travail, commit, critères et statuts renseignés',()=>{for(const x of ts){for(const k of ['id','title','commit','work','verify','refs','phase'])assert.ok(typeof x[k]==='string'&&x[k].trim());assert.match(x.commit,/^(feat|fix|test|docs|chore|refactor|ci|perf|style|build)\([^)]+\): .+/);assert.ok(['TODO','IN_PROGRESS','IN_REVIEW','DONE','BLOCKED'].includes(x.status),x.id);if(['IN_REVIEW','DONE'].includes(x.status)){assert.ok(Array.isArray(x.evidence)&&x.evidence.length>0,x.id+' sans preuve');x.evidence.forEach(p=>assert.ok(existsSync(resolve(root,p)),p));}}});
check('Brief et plan reprennent exactement les tâches actives',()=>{for(const p of ['HAAS_CODEX_MASTER.md','docs/execution/PLAN_COMMITS.md']){const matches=[...read(p).matchAll(/^####\s+([A-Z]+\d+)\s+—/gm)].map(m=>m[1]);assert.deepEqual(matches,ids,p);}});
check('AC01–AC90 uniques ; AC47 conditionnel',()=>{const a=read('docs/quality/ACCEPTANCE_MATRIX.md');const ids=[...a.matchAll(/^\| (AC\d{2}) \|/gm)].map(x=>x[1]);assert.deepEqual(ids,Array.from({length:90},(_,i)=>'AC'+String(i+1).padStart(2,'0')));assert.match(a,/\| AC47 \| P1 seulement/);});
check('23 familles UX réellement décrites',()=>{const a=read('docs/design/SCREEN_SPECIFICATIONS.md');const h=[...a.matchAll(/^## UX(\d{2}) —/gm)].map(x=>x[1]);assert.deepEqual(h,Array.from({length:23},(_,i)=>String(i+1).padStart(2,'0')));});
check('10 skills locaux ; front matter et métadonnées',()=>{const dir=resolve(root,'.agents/skills');const names=readdirSync(dir).filter(x=>statSync(resolve(dir,x)).isDirectory());assert.equal(names.length,10);for(const n of names){const a=read(`.agents/skills/${n}/SKILL.md`);assert.ok(a.startsWith('---\n'));assert.ok(a.includes(`name: ${n}\n`));assert.match(a,/^description: .+/m);assert.ok(existsSync(resolve(dir,n,'agents/openai.yaml')));}});
check('Mail source conservé et modalités distinguées',()=>{const a=read('docs/sources/MAIL_CADRAGE_CADEV.md');assert.ok(a.includes("Une plateforme d'échange pour les développeurs, par les développeurs et pour les développeurs."));assert.ok(a.includes('Il n’impose'));assert.ok(read('docs/product/ALIGNEMENT_MAIL.md').includes('Notre traduction produit'));assert.ok(existsSync(resolve(root,'docs/decisions/ADR-005-alignement-mail-cadev.md')));});
check('Projets, opt-in, questions et non-obligation du lab',()=>{const a=read('docs/product/COMMUNAUTE_ET_PROJETS.md');for(const x of ['F16','F17','ask_question','directory_visible','project_id','sans code','pas une condition'])assert.ok(a.includes(x),x);assert.ok(a.includes('jamais récupérés par le serveur'));});
check('61 sections du cahier et références de communauté',()=>{const a=read('docs/product/CAHIER_DES_CHARGES.md');const h=[...a.matchAll(/^## (\d{2}) —/gm)].map(x=>x[1]);assert.deepEqual(h,Array.from({length:61},(_,i)=>String(i+1).padStart(2,'0')));for(const k of ['F16','F17','AC68','UX23','122 lots'])assert.ok(a.includes(k),k);});
check('Livrables et instructions actifs présents',()=>{for(const p of ['livrables/HAAS_Cahier_des_charges.pdf','livrables/HAAS_Cahier_des_charges.html','livrables/HAAS_Presentation.pptx','livrables/HAAS_Presentation.pdf','docs/presentation/NOTES_ORATEUR.md','DEMARRER_CODEX.txt','AGENTS.md','backend/AGENTS.md','frontend/AGENTS.md','assets/brand/favicon.ico'])assert.ok(existsSync(resolve(root,p)),p);});
check('JSON livrés lisibles ; aucune police ou configuration .env privée suivie',()=>{for(const p of deliveredFiles){if(extname(p)==='.json')JSON.parse(readFileSync(p,'utf8'));assert.ok(!/\.(ttf|otf|woff2?|eot)$/i.test(p),relative(root,p));const name=basename(p);assert.ok(!(name==='.env'||(name.startsWith('.env.')&&!name.endsWith('.example'))),relative(root,p));}});
check('Dépendances explicites sans cycle ni lot futur',()=>{const positions=new Map(ids.map((x,i)=>[x,i]));for(const t of ts){for(const d of t.depends_on??[]){assert.ok(positions.has(d),d);assert.ok(positions.get(d)<positions.get(t.id),t.id+' dépend de '+d);}}});
check('Coup de main avant audits et gates',()=>{for(let i=1;i<=10;i++)assert.ok(ids.indexOf('BH'+String(i).padStart(2,'0'))<ids.indexOf('B39'));for(let i=1;i<=5;i++)assert.ok(ids.indexOf('FH'+String(i).padStart(2,'0'))<ids.indexOf('F23'));assert.ok(ids.indexOf('RH01')<ids.indexOf('R06'));});
check('Contrat F18 et distinctions essentielles présents',()=>{const a=read('docs/product/COUPS_DE_MAIN.md');for(const x of ['allow_public_summary','publish_consent','pending','accepted','declined','withdrawn','expired','Idempotency-Key','lock_version','directory_visible','pas un travail achevé'])assert.ok(a.includes(x),x);for(const p of ['docs/api/COUPS_DE_MAIN_API.md','docs/decisions/ADR-006-rencontre-par-coup-de-main.md','.agents/skills/haas-help-offers/SKILL.md'])assert.ok(existsSync(resolve(root,p)),p);});
check('Ancien cul-de-sac CTA retiré des consignes actives',()=>{for(const p of ['HAAS_CODEX_MASTER.md','docs/product/COMMUNAUTE_ET_PROJETS.md','docs/product/CAHIER_DES_CHARGES.md'])assert.ok(!read(p).includes('Si aucune demande n’est ouverte, afficher « Aucune demande d’aide ouverte pour ce projet »'),p);});
check('Anciennes sources non réécrites et absence de fausse implementation',()=>{const a=JSON.parse(read('MANIFEST.json'));assert.equal(a.app_implemented_in_this_archive,false);assert.equal(a.latest_decision,'ADR-006');assert.equal(a.acceptance_scenarios,90);assert.equal(a.screen_families,23);});

const fail=rows.filter(x=>x.status==='FAIL').length;console.log(JSON.stringify({scope:'Dossier documentaire seulement ; aucun test applicatif',date:new Date().toISOString(),checks:rows,passed:rows.length-fail,failed:fail},null,2));process.exit(fail?1:0);
